//
// Created by breuils on 2021/01/07.
//

#ifndef GADIGITALTRANSFO_GADIGITIIZEDTRANSFORMATIONPROPERTIES_H
#define GADIGITALTRANSFO_GADIGITIIZEDTRANSFORMATIONPROPERTIES_H

#endif //GADIGITALTRANSFO_GADIGITIIZEDTRANSFORMATIONPROPERTIES_H
